//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQuit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IQuit.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t feel like your crew is up to the mission? It&apos;s too late to quit! ... or is it?.
        /// </summary>
        internal static string CommandDesc {
            get {
                return ResourceManager.GetString("CommandDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your resignation has been refused by the Company. Only the Chief Officer can resign for the entire crew..
        /// </summary>
        internal static string HostOnly {
            get {
                return ResourceManager.GetString("HostOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request denied.
        /// </summary>
        internal static string RequestDenied {
            get {
                return ResourceManager.GetString("RequestDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request granted.
        /// </summary>
        internal static string RequestGranted {
            get {
                return ResourceManager.GetString("RequestGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your resignation has been accepted. Please return any Company&apos;s issued property before leaving the ship.
        ///Your termination is effective immediately..
        /// </summary>
        internal static string ReturnEquipment {
            get {
                return ResourceManager.GetString("ReturnEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending resignation request... Please wait....
        /// </summary>
        internal static string SendingResignation {
            get {
                return ResourceManager.GetString("SendingResignation", resourceCulture);
            }
        }
    }
}
